version: "3"
services:

  centos:
    container_name: "centos"
    build: 
      context: ./build/centos/${CENTOS_VERSION}
      #dockerfile: Dockerfile
      args:
        CENTOS_VERSION: ${CENTOS_VERSION}
        TZ: ${TZ}
    volumes:
      - ${APPPATH}:${WWWHTML}:rw
      - ${CENTOS_SSH_PATH}:/root/.ssh/:rw
    restart: always
    ports:
      - "22222:22"
    privileged: true
    #user: root
    environment:
      TZ: "$TZ" 
    networks:
      - default

  nginx:
    container_name: "nginx"
    build: 
      context: ./build/nginx/${NGINX_VERSION}
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        TZ: ${TZ}
        WWWHTML: ${WWWHTML}
    volumes:
      - ${APPPATH}:${WWWHTML}:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    privileged: true
    environment:
      TZ: "$TZ" 
    networks:
      - default

  mysql:
    container_name: "mysql"
    build: 
      context: ./build/mysql/${MYSQL_VERSION}
      args:
        TZ: ${TZ}
        MYSQL_VERSION: ${MYSQL_VERSION}
    volumes:
      - ${MYSQL_CONF_DIR}:/etc/mysql/conf.d/:rw
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
      - ${MYSQL_CONF_FILE}:/etc/my.cnf:ro
    restart: always
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    privileged: true
    networks:
      - default

  php-fpm:
    container_name: "php"
    build:
      context: ./build/php/${PHP_VERSION}
      args:
        TZ: "$TZ"
        PHP_VERSION: ${PHP_VERSION}
        PHP_VERSION_FPM: ${PHP_VERSION_FPM}
        PHP_EXTENSIONS: ${PHP_EXTENSIONS}
        WWWHTML: ${WWWHTML}
    ports:
      - "${PHP_HOST_PORT}:9000"
    privileged: true
    volumes:
      - ${APPPATH}:${WWWHTML}:rw
      - ${PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php/:rw
    restart: always
    # cap_add:
    #   - SYS_PTRACE
    # stdin_open: true
    # tty: true
    networks:
      - default

  redis:
    container_name: "redis"
    build:
      context: ./build/redis/${REDIS_VERSION}
      args:
        TZ: "$TZ"
        REDIS_VERSION: ${REDIS_VERSION}
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]
    privileged: true
    networks:
      - default

  node:
    container_name: "node"
    build:
      context: ./build/node/${NODE_VERSION}
      args:
        TZ: "$TZ"
        NODE_VERSION: ${NODE_VERSION}
    privileged: true
    volumes:
      - ${APPPATH}:${WWWHTML}:rw
    environment:
      TZ: "$TZ"
    stdin_open: true
    tty: true  
    networks:
      - default

networks:
  default:


